name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-versions }}
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Build
      run: |
        npx yarn
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        local-dir: ./build/
        server-dir: ./lire-la-musique/
